
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fc31f9480d0>
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/amohamed/huudeey/django/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/amohamed/huudeey/django/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 394, in check
    for pattern in self.url_patterns:
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 531, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 524, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huudeey/urls.py", line 26, in <module>
    path('huud/', include('huud.urls')),
  File "/home/amohamed/huudeey/django/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/urls.py", line 9, in <module>
    path('saledate/', views.prodsale.as_view(), name='saledate'),
AttributeError: 'function' object has no attribute 'as_view'
Performing system checks...

[18/Feb/2018 22:37:10] "GET /huud/saledate/ HTTP/1.1" 200 379
[19/Feb/2018 01:55:50] "GET /huud/saledate/ HTTP/1.1" 200 380
Not Found: /saledate/
[19/Feb/2018 01:55:56] "POST /saledate/ HTTP/1.1" 404 2301
Not Found: /saledate
[19/Feb/2018 01:56:07] "GET /saledate HTTP/1.1" 404 2297
Not Found: /saledate
[19/Feb/2018 01:56:10] "GET /saledate HTTP/1.1" 404 2297
[19/Feb/2018 01:56:25] "GET / HTTP/1.1" 302 0
[19/Feb/2018 01:56:25] "GET /huud/ HTTP/1.1" 200 1304
/home/amohamed/huudeey/django/django/views/generic/list.py:88: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'huud.models.Prodsale'> QuerySet.
  allow_empty_first_page=allow_empty_first_page, **kwargs)
[19/Feb/2018 01:56:44] "GET /huud/sales/ HTTP/1.1" 200 14837
[19/Feb/2018 01:56:55] "GET /huud/saledate/ HTTP/1.1" 200 380
Not Found: /saledate/
[19/Feb/2018 01:57:01] "POST /saledate/ HTTP/1.1" 404 2301
Not Found: /saledate
[19/Feb/2018 01:57:53] "GET /saledate HTTP/1.1" 404 2297
[19/Feb/2018 01:58:07] "GET /huud/saledate/ HTTP/1.1" 200 380
Unknown command: 'runsever'
Type 'manage.py help' for usage.
/home/amohamed/huudeey/django/django/views/generic/list.py:88: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'huud.models.Prodsale'> QuerySet.
  allow_empty_first_page=allow_empty_first_page, **kwargs)
[20/Feb/2018 16:38:42] "GET /huud/sales/ HTTP/1.1" 200 14837
[20/Feb/2018 16:38:42] "GET /static/css/styles.css HTTP/1.1" 304 0
Not Found: /favicon.ico
[20/Feb/2018 16:38:43] "GET /favicon.ico HTTP/1.1" 404 2306
[20/Feb/2018 16:39:26] "GET /huud/ HTTP/1.1" 200 1304
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 20, 2018 - 16:35:54
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f379977e0d0>
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/amohamed/huudeey/django/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/amohamed/huudeey/django/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 531, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 524, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huudeey/urls.py", line 26, in <module>
    path('huud/', include('huud.urls')),
  File "/home/amohamed/huudeey/django/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/urls.py", line 3, in <module>
    from . import views
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 33
    ctx.update({'prod_list': prod_list})A
                                        ^
SyntaxError: invalid syntax
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7ff0309f70d0>
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/amohamed/huudeey/django/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/amohamed/huudeey/django/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 394, in check
    for pattern in self.url_patterns:
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 531, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 524, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huudeey/urls.py", line 26, in <module>
    path('huud/', include('huud.urls')),
  File "/home/amohamed/huudeey/django/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/urls.py", line 8, in <module>
    path('sales/', views.ProdsaleListView.as_view(model=Prodsale), name='sales'),
NameError: name 'Prodsale' is not defined
Performing system checks...

Unknown command: 'runsever'
Type 'manage.py help' for usage.
Unknown command: 'runsever'
Type 'manage.py help' for usage.
Internal Server Error: /huud/sales/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/django/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/amohamed/huudeey/django/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/amohamed/huudeey/django/django/views/generic/list.py", line 157, in get
    context = self.get_context_data()
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 31, in get_context_data
    prod_list = self.object.Prodsale.filter(prodname='BELT')
AttributeError: 'ProdsaleListView' object has no attribute 'object'
[20/Feb/2018 19:20:11] "GET /huud/sales/ HTTP/1.1" 500 78671
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 20, 2018 - 19:19:59
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /huud/sales/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/django/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/amohamed/huudeey/django/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/amohamed/huudeey/django/django/views/generic/list.py", line 157, in get
    context = self.get_context_data()
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 30, in get_context_data
    ctx = super(self).get_context_data(**kwargs)
TypeError: super() argument 1 must be type, not ProdsaleListView
[20/Feb/2018 19:21:58] "GET /huud/sales/ HTTP/1.1" 500 76463
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 20, 2018 - 19:21:52
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f97aad020d0>
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/amohamed/huudeey/django/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/amohamed/huudeey/django/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 531, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 524, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huudeey/urls.py", line 26, in <module>
    path('huud/', include('huud.urls')),
  File "/home/amohamed/huudeey/django/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/urls.py", line 3, in <module>
    from . import views
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 30
    ctx = super(self).get_context_data(,**kwargs)
                                       ^
SyntaxError: invalid syntax
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f0e8bd830d0>
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/amohamed/huudeey/django/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/amohamed/huudeey/django/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 394, in check
    for pattern in self.url_patterns:
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 531, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 524, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huudeey/urls.py", line 26, in <module>
    path('huud/', include('huud.urls')),
  File "/home/amohamed/huudeey/django/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/urls.py", line 3, in <module>
    from . import views
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 30
    ctx = super(self).get_context_data(,**kwargs)
                                       ^
SyntaxError: invalid syntax
Performing system checks...

Internal Server Error: /huud/sales/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/django/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/amohamed/huudeey/django/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/amohamed/huudeey/django/django/views/generic/list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 30, in get_queryset
    return  Prodsale.objects.Prodsale.filter(prodname__icontains='BELT')
AttributeError: 'Manager' object has no attribute 'Prodsale'
[20/Feb/2018 19:30:13] "GET /huud/sales/ HTTP/1.1" 500 75868
[20/Feb/2018 19:30:47] "GET /admin/ HTTP/1.1" 200 3612
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 20, 2018 - 19:30:06
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fea6b9640d0>
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/amohamed/huudeey/django/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/amohamed/huudeey/django/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 394, in check
    for pattern in self.url_patterns:
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 531, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 524, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huudeey/urls.py", line 26, in <module>
    path('huud/', include('huud.urls')),
  File "/home/amohamed/huudeey/django/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/urls.py", line 3, in <module>
    from . import views
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 27, in <module>
    class ProdsaleListView(generic.ListView):
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 28, in ProdsaleListView
    model = Prodsales
NameError: name 'Prodsales' is not defined
Performing system checks...

[20/Feb/2018 19:32:57] "GET /admin/ HTTP/1.1" 200 3612
[20/Feb/2018 19:33:17] "GET /huud/sales/ HTTP/1.1" 200 7426
[20/Feb/2018 20:11:12] "GET /huud/saledate/ HTTP/1.1" 200 1247
[20/Feb/2018 20:11:14] "GET /huud/ HTTP/1.1" 200 1304
[20/Feb/2018 20:11:24] "GET /huud/saledate/ HTTP/1.1" 200 1247
Not Found: /saledate/
[20/Feb/2018 20:11:30] "POST /saledate/ HTTP/1.1" 404 2301
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 20, 2018 - 19:32:55
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[20/Feb/2018 21:33:36] "GET /huud/saledate/ HTTP/1.1" 200 1247
Not Found: /saledate/
[20/Feb/2018 21:33:40] "POST /saledate/ HTTP/1.1" 404 2301
[20/Feb/2018 21:46:18] "GET /huud/sales/ HTTP/1.1" 200 7426
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 20, 2018 - 21:33:22
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[20/Feb/2018 21:55:44] "GET /huud/saledate/ HTTP/1.1" 200 1247
Not Found: /saledate/
[20/Feb/2018 21:55:48] "POST /saledate/ HTTP/1.1" 404 2301
[20/Feb/2018 22:00:42] "GET /huud/saledate/ HTTP/1.1" 200 1256
Not Found: /huud/saledate/{% 'result.html' }}
[20/Feb/2018 22:00:48] "POST /huud/saledate/%7B%%20'result.html'%20%7D%7D HTTP/1.1" 404 2820
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 20, 2018 - 21:54:45
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7feaf07390d0>
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/amohamed/huudeey/django/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/amohamed/huudeey/django/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 531, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 524, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huudeey/urls.py", line 26, in <module>
    path('huud/', include('huud.urls')),
  File "/home/amohamed/huudeey/django/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/urls.py", line 3, in <module>
    from . import views
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 51
    return render(request, 'result.html', context={'content':content )
                                                                     ^
SyntaxError: invalid syntax
Performing system checks...

[21/Feb/2018 14:28:04] "GET /huud/saledate/ HTTP/1.1" 200 1247
Not Found: /saledate/
[21/Feb/2018 14:28:08] "POST /saledate/ HTTP/1.1" 404 2301
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 14:25:57
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7feb905220d0>
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/amohamed/huudeey/django/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/amohamed/huudeey/django/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 394, in check
    for pattern in self.url_patterns:
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 531, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 524, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huudeey/urls.py", line 26, in <module>
    path('huud/', include('huud.urls')),
  File "/home/amohamed/huudeey/django/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/urls.py", line 11, in <module>
    path('results/', views.results, name='results'),
AttributeError: module 'huud.views' has no attribute 'results'
Performing system checks...

[21/Feb/2018 14:56:42] "GET /huud/saledate/ HTTP/1.1" 200 1247
Not Found: /favicon.ico
[21/Feb/2018 14:56:43] "GET /favicon.ico HTTP/1.1" 404 2306
Not Found: /saledate/
[21/Feb/2018 14:56:48] "POST /saledate/ HTTP/1.1" 404 2301
[21/Feb/2018 14:58:32] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 48, in prodsale
    content = form.clean_data['prodname']
AttributeError: 'saledateform' object has no attribute 'clean_data'
[21/Feb/2018 14:58:38] "POST /huud/saledate/ HTTP/1.1" 500 63755
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 48, in prodsale
    content = form.clean_data['prodname']
AttributeError: 'saledateform' object has no attribute 'clean_data'
[21/Feb/2018 15:11:02] "POST /huud/saledate/ HTTP/1.1" 500 63755
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 14:56:26
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[21/Feb/2018 15:36:18] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 48, in prodsale
    content = form.clean_data['prodname']
AttributeError: 'saledateform' object has no attribute 'clean_data'
[21/Feb/2018 15:36:27] "POST /huud/saledate/ HTTP/1.1" 500 63755
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 15:36:12
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[21/Feb/2018 15:38:14] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 48, in prodsale
    content = form.clean_data[ 'prodname' ]
AttributeError: 'saledateform' object has no attribute 'clean_data'
[21/Feb/2018 15:38:27] "POST /huud/saledate/ HTTP/1.1" 500 63562
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 15:38:07
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[21/Feb/2018 15:39:53] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 51, in prodsale
    return redirect('resutls', content_all=content )
NameError: name 'redirect' is not defined
[21/Feb/2018 15:39:57] "POST /huud/saledate/ HTTP/1.1" 500 63520
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 15:39:47
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
System check identified some issues:

WARNINGS:
?: (2_0.W001) Your URL pattern '^results/' [name='results'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().

System check identified 1 issue (0 silenced).
[21/Feb/2018 15:45:21] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 51, in prodsale
    return redirect('resutls', content_all=content )
NameError: name 'redirect' is not defined
[21/Feb/2018 15:45:28] "POST /huud/saledate/ HTTP/1.1" 500 63520
Performing system checks...


You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 15:45:17
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
System check identified some issues:

WARNINGS:
?: (2_0.W001) Your URL pattern '^results/' [name='results'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().

System check identified 1 issue (0 silenced).
[21/Feb/2018 15:46:45] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 51, in prodsale
    return redirect('results', content_all=content )
NameError: name 'redirect' is not defined
[21/Feb/2018 15:46:51] "POST /huud/saledate/ HTTP/1.1" 500 63520
Performing system checks...


You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 15:46:41
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
System check identified some issues:

WARNINGS:
?: (2_0.W001) Your URL pattern '^results/' [name='results'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().

System check identified 1 issue (0 silenced).
[21/Feb/2018 15:48:13] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 51, in prodsale
    return redirect('results')
NameError: name 'redirect' is not defined
[21/Feb/2018 15:48:17] "POST /huud/saledate/ HTTP/1.1" 500 63476
Performing system checks...


You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 15:48:09
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
System check identified some issues:

WARNINGS:
?: (2_0.W001) Your URL pattern '^results/' [name='results'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().

System check identified 1 issue (0 silenced).
[21/Feb/2018 15:50:24] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 51, in prodsale
    return redirect('huud/results')
NameError: name 'redirect' is not defined
[21/Feb/2018 15:50:31] "POST /huud/saledate/ HTTP/1.1" 500 63486
Performing system checks...


You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 15:50:19
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
System check identified some issues:

WARNINGS:
?: (2_0.W001) Your URL pattern '^results/' [name='results'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().

System check identified 1 issue (0 silenced).
Performing system checks...


You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 15:51:13
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[21/Feb/2018 15:51:35] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 51, in prodsale
    return redirect('huud/results')
NameError: name 'redirect' is not defined
[21/Feb/2018 15:51:40] "POST /huud/saledate/ HTTP/1.1" 500 63486
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 15:51:31
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[21/Feb/2018 15:53:17] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 51, in prodsale
    return redirect('huudeey/huud/results')
NameError: name 'redirect' is not defined
[21/Feb/2018 15:53:21] "POST /huud/saledate/ HTTP/1.1" 500 63502
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 15:53:13
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 52, in prodsale
    return redirect('huudeey/huud/results')
NameError: name 'redirect' is not defined
[21/Feb/2018 15:57:29] "POST /huud/saledate/ HTTP/1.1" 500 63502
[21/Feb/2018 15:57:35] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 52, in prodsale
    return redirect('huudeey/huud/results')
NameError: name 'redirect' is not defined
[21/Feb/2018 15:57:41] "POST /huud/saledate/ HTTP/1.1" 500 63502
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 15:57:27
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[21/Feb/2018 16:01:01] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 52, in prodsale
    return redirect('results')
NameError: name 'redirect' is not defined
[21/Feb/2018 16:01:04] "POST /huud/saledate/ HTTP/1.1" 500 63476
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 16:00:56
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[21/Feb/2018 16:02:25] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 52, in prodsale
    return redirect('results')
NameError: name 'redirect' is not defined
[21/Feb/2018 16:02:31] "POST /huud/saledate/ HTTP/1.1" 500 63476
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 16:02:21
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[21/Feb/2018 16:04:04] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 53, in prodsale
    return redirect('results')
NameError: name 'redirect' is not defined
[21/Feb/2018 16:04:08] "POST /huud/saledate/ HTTP/1.1" 500 63476
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 16:03:59
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[21/Feb/2018 16:20:40] "GET /huud/saledate/ HTTP/1.1" 200 1237
[21/Feb/2018 16:20:44] "POST /huud/saledate/ HTTP/1.1" 302 0
Internal Server Error: /huud/results/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: results() missing 1 required positional argument: 'content_all'
[21/Feb/2018 16:20:44] "GET /huud/results/ HTTP/1.1" 500 59050
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 16:20:35
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[21/Feb/2018 16:21:40] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 54, in prodsale
    return redirect('results', content_all=content)
  File "/home/amohamed/huudeey/django/django/shortcuts.py", line 58, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/home/amohamed/huudeey/django/django/shortcuts.py", line 149, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/home/amohamed/huudeey/django/django/urls/base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'results' with keyword arguments '{'content_all': 'BABY'}' not found. 1 pattern(s) tried: ['huud\\/results\\/$']
[21/Feb/2018 16:21:44] "POST /huud/saledate/ HTTP/1.1" 500 83838
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 16:21:36
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[21/Feb/2018 16:25:52] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 54, in prodsale
    return redirect('results', content_all=content)
  File "/home/amohamed/huudeey/django/django/shortcuts.py", line 58, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/home/amohamed/huudeey/django/django/shortcuts.py", line 149, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/home/amohamed/huudeey/django/django/urls/base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'results' with keyword arguments '{'content_all': 'BABY'}' not found. 1 pattern(s) tried: ['huud\\/results\\/$']
[21/Feb/2018 16:25:56] "POST /huud/saledate/ HTTP/1.1" 500 83838
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 16:25:48
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[21/Feb/2018 16:27:25] "GET /huud/saledate/ HTTP/1.1" 200 1237
Internal Server Error: /huud/saledate/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 54, in prodsale
    return redirect('results', content)
  File "/home/amohamed/huudeey/django/django/shortcuts.py", line 58, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/home/amohamed/huudeey/django/django/shortcuts.py", line 149, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/home/amohamed/huudeey/django/django/urls/base.py", line 88, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'results' with arguments '('BABY',)' not found. 1 pattern(s) tried: ['huud\\/results\\/$']
[21/Feb/2018 16:27:29] "POST /huud/saledate/ HTTP/1.1" 500 83546
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 16:27:21
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f7f050620d0>
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/amohamed/huudeey/django/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/amohamed/huudeey/django/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 531, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 524, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huudeey/urls.py", line 26, in <module>
    path('huud/', include('huud.urls')),
  File "/home/amohamed/huudeey/django/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/urls.py", line 3, in <module>
    from . import views
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 64
    return render(request, 'results.html' , {'content':content )
                                                               ^
SyntaxError: invalid syntax
Performing system checks...

Unknown command: 'renserver'
Type 'manage.py help' for usage.
[21/Feb/2018 18:51:58] "GET /huud/saledate/ HTTP/1.1" 200 1237
[21/Feb/2018 18:52:01] "POST /huud/saledate/ HTTP/1.1" 302 0
Internal Server Error: /huud/results/BABY/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 64, in results
    return render(request, 'results.html' , {'content':content} )
  File "/home/amohamed/huudeey/django/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/amohamed/huudeey/django/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/amohamed/huudeey/django/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: results.html
[21/Feb/2018 18:52:02] "GET /huud/results/BABY/ HTTP/1.1" 500 79565
[21/Feb/2018 18:53:18] "GET /huud/saledate/ HTTP/1.1" 200 1237
[21/Feb/2018 18:53:22] "POST /huud/saledate/ HTTP/1.1" 302 0
Internal Server Error: /huud/results/BABY/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 64, in results
    return render(request, 'results.html' , {'content':content} )
  File "/home/amohamed/huudeey/django/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/amohamed/huudeey/django/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/amohamed/huudeey/django/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: results.html
[21/Feb/2018 18:53:22] "GET /huud/results/BABY/ HTTP/1.1" 500 79565
[21/Feb/2018 18:53:44] "GET /huud/saledate/ HTTP/1.1" 200 1237
[21/Feb/2018 18:53:47] "POST /huud/saledate/ HTTP/1.1" 302 0
[21/Feb/2018 18:53:47] "GET /huud/results/BABY/ HTTP/1.1" 200 875
[21/Feb/2018 18:54:08] "GET /huud/saledate/ HTTP/1.1" 200 1237
[21/Feb/2018 18:54:13] "POST /huud/saledate/ HTTP/1.1" 302 0
[21/Feb/2018 18:54:13] "GET /huud/results/BELT/ HTTP/1.1" 200 875
[21/Feb/2018 18:54:55] "GET /huud/saledate/ HTTP/1.1" 200 1237
[21/Feb/2018 18:54:59] "POST /huud/saledate/ HTTP/1.1" 302 0
[21/Feb/2018 18:54:59] "GET /huud/results/BABY/ HTTP/1.1" 200 1754
[21/Feb/2018 18:56:07] "GET /huud/saledate/ HTTP/1.1" 200 1237
[21/Feb/2018 18:56:10] "POST /huud/saledate/ HTTP/1.1" 302 0
[21/Feb/2018 18:56:10] "GET /huud/results/BABY/ HTTP/1.1" 200 875
[21/Feb/2018 18:59:22] "GET /huud/saledate/ HTTP/1.1" 200 1237
[21/Feb/2018 18:59:26] "POST /huud/saledate/ HTTP/1.1" 302 0
[21/Feb/2018 18:59:26] "GET /huud/results/BABY/ HTTP/1.1" 200 1948
[21/Feb/2018 19:05:37] "GET /huud/saledate/ HTTP/1.1" 200 1237
[21/Feb/2018 19:05:44] "POST /huud/saledate/ HTTP/1.1" 302 0
[21/Feb/2018 19:05:44] "GET /huud/results/BELT/ HTTP/1.1" 200 5758
[21/Feb/2018 19:06:00] "GET /huud/saledate/ HTTP/1.1" 200 1237
[21/Feb/2018 19:06:15] "POST /huud/saledate/ HTTP/1.1" 302 0
[21/Feb/2018 19:06:15] "GET /huud/results/BABY/ HTTP/1.1" 200 5320
[21/Feb/2018 19:06:44] "GET /huud/ HTTP/1.1" 200 1304
[21/Feb/2018 19:06:49] "GET /huud/saledate/ HTTP/1.1" 200 1237
[21/Feb/2018 19:07:25] "POST /huud/saledate/ HTTP/1.1" 302 0
[21/Feb/2018 19:07:25] "GET /huud/results/House/ HTTP/1.1" 200 8995
[21/Feb/2018 19:07:44] "GET /huud/saledate/ HTTP/1.1" 200 1237
[21/Feb/2018 19:07:50] "POST /huud/saledate/ HTTP/1.1" 302 0
[21/Feb/2018 19:07:51] "GET /huud/results/MEN/ HTTP/1.1" 200 18282
[21/Feb/2018 19:08:13] "GET /huud/saledate/ HTTP/1.1" 200 1237
[21/Feb/2018 19:09:19] "GET /huud/ HTTP/1.1" 200 1304
[21/Feb/2018 19:09:26] "GET /huud/saledate/ HTTP/1.1" 200 1237
[21/Feb/2018 19:09:32] "POST /huud/saledate/ HTTP/1.1" 302 0
[21/Feb/2018 19:09:32] "GET /huud/results/G/ HTTP/1.1" 200 27604
[21/Feb/2018 19:09:59] "GET /huud/ HTTP/1.1" 200 1304
[21/Feb/2018 19:10:18] "GET /huud/saledate/ HTTP/1.1" 200 1237
[21/Feb/2018 19:18:24] "GET /huud/ HTTP/1.1" 200 1151
[21/Feb/2018 19:18:31] "GET /huud/saledate/ HTTP/1.1" 200 1292
[21/Feb/2018 19:19:04] "POST /huud/saledate/ HTTP/1.1" 302 0
[21/Feb/2018 19:19:04] "GET /huud/results/LAD/ HTTP/1.1" 200 36122
[21/Feb/2018 19:19:24] "GET /huud/ HTTP/1.1" 200 1151
[21/Feb/2018 19:20:20] "GET /huud/saledate/ HTTP/1.1" 200 1292
[21/Feb/2018 19:20:32] "POST /huud/saledate/ HTTP/1.1" 302 0
[21/Feb/2018 19:20:32] "GET /huud/results/TO/ HTTP/1.1" 200 11781
[21/Feb/2018 19:41:10] "GET /huud/ HTTP/1.1" 200 1151
[21/Feb/2018 19:41:11] "GET /huud/saledate/ HTTP/1.1" 200 1292
[21/Feb/2018 19:41:17] "POST /huud/saledate/ HTTP/1.1" 302 0
[21/Feb/2018 19:41:17] "GET /huud/results/CUR/ HTTP/1.1" 200 3375
[21/Feb/2018 19:41:50] "GET /huud/ HTTP/1.1" 200 1151
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 18:51:50
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fe9f91620d0>
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/amohamed/huudeey/django/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/amohamed/huudeey/django/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 531, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 524, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huudeey/urls.py", line 26, in <module>
    path('huud/', include('huud.urls')),
  File "/home/amohamed/huudeey/django/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/urls.py", line 4, in <module>
    from . import views
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 40, in <module>
    from .forms import saledateform
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/forms.py", line 4, in <module>
    from django import datetime
ImportError: cannot import name 'datetime'
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f19768e50d0>
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/amohamed/huudeey/django/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/amohamed/huudeey/django/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/amohamed/huudeey/django/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/amohamed/huudeey/django/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 531, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/amohamed/huudeey/django/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/amohamed/huudeey/django/django/urls/resolvers.py", line 524, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huudeey/urls.py", line 26, in <module>
    path('huud/', include('huud.urls')),
  File "/home/amohamed/huudeey/django/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/amohamed/huudeey/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/urls.py", line 4, in <module>
    from . import views
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 40, in <module>
    from .forms import saledateform
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/forms.py", line 4, in <module>
    from django import datetime
ImportError: cannot import name 'datetime'
Performing system checks...

[21/Feb/2018 22:14:49] "GET /huud/searchdatesale/ HTTP/1.1" 200 3079
[21/Feb/2018 22:14:50] "POST /huud/searchdatesale/ HTTP/1.1" 200 3106
[21/Feb/2018 22:14:52] "POST /huud/searchdatesale/ HTTP/1.1" 200 3106
[21/Feb/2018 22:14:55] "POST /huud/searchdatesale/ HTTP/1.1" 200 3106
[21/Feb/2018 22:17:42] "POST /huud/searchdatesale/ HTTP/1.1" 200 3106
[21/Feb/2018 22:17:45] "POST /huud/searchdatesale/ HTTP/1.1" 200 3106
[21/Feb/2018 22:17:48] "GET /huud/searchdatesale/ HTTP/1.1" 200 3079
[21/Feb/2018 22:17:50] "POST /huud/searchdatesale/ HTTP/1.1" 200 3106
[21/Feb/2018 22:18:26] "POST /huud/searchdatesale/ HTTP/1.1" 200 3106
[21/Feb/2018 22:18:28] "POST /huud/searchdatesale/ HTTP/1.1" 200 3106
[21/Feb/2018 22:18:29] "POST /huud/searchdatesale/ HTTP/1.1" 200 3106
[22/Feb/2018 18:57:04] "GET /huud/saledate/ HTTP/1.1" 200 1320
[22/Feb/2018 18:57:04] "GET /static/css/styles.css HTTP/1.1" 304 0
[22/Feb/2018 19:00:05] "GET /huud/searchdatesale/ HTTP/1.1" 200 3104
[22/Feb/2018 19:04:30] "GET /huud/searchdatesale/ HTTP/1.1" 200 3082
[22/Feb/2018 19:04:32] "POST /huud/searchdatesale/ HTTP/1.1" 200 3109
[22/Feb/2018 19:04:35] "POST /huud/searchdatesale/ HTTP/1.1" 200 3109
[22/Feb/2018 19:04:37] "GET /huud/saledate/ HTTP/1.1" 200 1293
[22/Feb/2018 19:04:40] "GET /huud/ HTTP/1.1" 200 1151
[22/Feb/2018 19:04:44] "GET /huud/searchdatesale/ HTTP/1.1" 200 3082
[22/Feb/2018 19:04:46] "POST /huud/searchdatesale/ HTTP/1.1" 200 3109
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 21, 2018 - 22:14:42
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[22/Feb/2018 19:05:48] "POST /huud/searchdatesale/ HTTP/1.1" 200 3109
[22/Feb/2018 19:05:55] "GET /huud/searchdatesale/ HTTP/1.1" 200 3082
[22/Feb/2018 19:05:56] "POST /huud/searchdatesale/ HTTP/1.1" 200 3109
[22/Feb/2018 19:06:02] "POST /huud/searchdatesale/ HTTP/1.1" 200 3109
[22/Feb/2018 19:06:07] "POST /huud/searchdatesale/ HTTP/1.1" 200 3109
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 22, 2018 - 19:05:45
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[22/Feb/2018 19:23:05] "GET /huud/searchdatesale/ HTTP/1.1" 200 3082
[22/Feb/2018 19:23:07] "POST /huud/searchdatesale/ HTTP/1.1" 302 0
Internal Server Error: /huud/searchdresults/{'t_result': <QuerySet [<Prodsale: Prodsale object (434)>, <Prodsale: Prodsale object (435)>, <Prodsale: Prodsale object (436)>, <Prodsale: Prodsale object (437)>, <Prodsale: Prodsale object (438)>, <Prodsale: Prodsale object (439)>, <Prodsale: Prodsale object (440)>, <Prodsale: Prodsale object (441)>, <Prodsale: Prodsale object (442)>, <Prodsale: Prodsale object (443)>, <Prodsale: Prodsale object (444)>, <Prodsale: Prodsale object (445)>, <Prodsale: Prodsale object (446)>, <Prodsale: Prodsale object (447)>, <Prodsale: Prodsale object (448)>, <Prodsale: Prodsale object (449)>, <Prodsale: Prodsale object (450)>, <Prodsale: Prodsale object (466)>, <Prodsale: Prodsale object (467)>, <Prodsale: Prodsale object (468)>, '...(remaining elements truncated)...']>}/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: searchdresults() got an unexpected keyword argument 't_result'
[22/Feb/2018 19:23:07] "GET /huud/searchdresults/%7B't_result':%20%3CQuerySet%20%5B%3CProdsale:%20Prodsale%20object%20(434)%3E,%20%3CProdsale:%20Prodsale%20object%20(435)%3E,%20%3CProdsale:%20Prodsale%20object%20(436)%3E,%20%3CProdsale:%20Prodsale%20object%20(437)%3E,%20%3CProdsale:%20Prodsale%20object%20(438)%3E,%20%3CProdsale:%20Prodsale%20object%20(439)%3E,%20%3CProdsale:%20Prodsale%20object%20(440)%3E,%20%3CProdsale:%20Prodsale%20object%20(441)%3E,%20%3CProdsale:%20Prodsale%20object%20(442)%3E,%20%3CProdsale:%20Prodsale%20object%20(443)%3E,%20%3CProdsale:%20Prodsale%20object%20(444)%3E,%20%3CProdsale:%20Prodsale%20object%20(445)%3E,%20%3CProdsale:%20Prodsale%20object%20(446)%3E,%20%3CProdsale:%20Prodsale%20object%20(447)%3E,%20%3CProdsale:%20Prodsale%20object%20(448)%3E,%20%3CProdsale:%20Prodsale%20object%20(449)%3E,%20%3CProdsale:%20Prodsale%20object%20(450)%3E,%20%3CProdsale:%20Prodsale%20object%20(466)%3E,%20%3CProdsale:%20Prodsale%20object%20(467)%3E,%20%3CProdsale:%20Prodsale%20object%20(468)%3E,%20'...(remaining%20elements%20truncated)...'%5D%3E%7D/ HTTP/1.1" 500 73414
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 22, 2018 - 19:22:56
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[22/Feb/2018 19:24:28] "GET /huud/searchdatesale/ HTTP/1.1" 200 3082
[22/Feb/2018 19:24:29] "POST /huud/searchdatesale/ HTTP/1.1" 302 0
Internal Server Error: /huud/searchdresults/{'t_result': <QuerySet [<Prodsale: Prodsale object (434)>, <Prodsale: Prodsale object (435)>, <Prodsale: Prodsale object (436)>, <Prodsale: Prodsale object (437)>, <Prodsale: Prodsale object (438)>, <Prodsale: Prodsale object (439)>, <Prodsale: Prodsale object (440)>, <Prodsale: Prodsale object (441)>, <Prodsale: Prodsale object (442)>, <Prodsale: Prodsale object (443)>, <Prodsale: Prodsale object (444)>, <Prodsale: Prodsale object (445)>, <Prodsale: Prodsale object (446)>, <Prodsale: Prodsale object (447)>, <Prodsale: Prodsale object (448)>, <Prodsale: Prodsale object (449)>, <Prodsale: Prodsale object (450)>, <Prodsale: Prodsale object (466)>, <Prodsale: Prodsale object (467)>, <Prodsale: Prodsale object (468)>, '...(remaining elements truncated)...']>}/
Traceback (most recent call last):
  File "/home/amohamed/huudeey/django/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/amohamed/huudeey/django/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/amohamed/huudeey/huudeey/huudeey/huud/views.py", line 95, in searchdresults
    content = pdate
NameError: name 'pdate' is not defined
[22/Feb/2018 19:24:30] "GET /huud/searchdresults/%7B't_result':%20%3CQuerySet%20%5B%3CProdsale:%20Prodsale%20object%20(434)%3E,%20%3CProdsale:%20Prodsale%20object%20(435)%3E,%20%3CProdsale:%20Prodsale%20object%20(436)%3E,%20%3CProdsale:%20Prodsale%20object%20(437)%3E,%20%3CProdsale:%20Prodsale%20object%20(438)%3E,%20%3CProdsale:%20Prodsale%20object%20(439)%3E,%20%3CProdsale:%20Prodsale%20object%20(440)%3E,%20%3CProdsale:%20Prodsale%20object%20(441)%3E,%20%3CProdsale:%20Prodsale%20object%20(442)%3E,%20%3CProdsale:%20Prodsale%20object%20(443)%3E,%20%3CProdsale:%20Prodsale%20object%20(444)%3E,%20%3CProdsale:%20Prodsale%20object%20(445)%3E,%20%3CProdsale:%20Prodsale%20object%20(446)%3E,%20%3CProdsale:%20Prodsale%20object%20(447)%3E,%20%3CProdsale:%20Prodsale%20object%20(448)%3E,%20%3CProdsale:%20Prodsale%20object%20(449)%3E,%20%3CProdsale:%20Prodsale%20object%20(450)%3E,%20%3CProdsale:%20Prodsale%20object%20(466)%3E,%20%3CProdsale:%20Prodsale%20object%20(467)%3E,%20%3CProdsale:%20Prodsale%20object%20(468)%3E,%20'...(remaining%20elements%20truncated)...'%5D%3E%7D/ HTTP/1.1" 500 78324
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 22, 2018 - 19:24:24
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[22/Feb/2018 19:25:04] "GET /huud/searchdatesale/ HTTP/1.1" 200 3082
[22/Feb/2018 19:25:06] "POST /huud/searchdatesale/ HTTP/1.1" 302 0
[22/Feb/2018 19:25:06] "GET /huud/searchdresults/%7B't_result':%20%3CQuerySet%20%5B%3CProdsale:%20Prodsale%20object%20(434)%3E,%20%3CProdsale:%20Prodsale%20object%20(435)%3E,%20%3CProdsale:%20Prodsale%20object%20(436)%3E,%20%3CProdsale:%20Prodsale%20object%20(437)%3E,%20%3CProdsale:%20Prodsale%20object%20(438)%3E,%20%3CProdsale:%20Prodsale%20object%20(439)%3E,%20%3CProdsale:%20Prodsale%20object%20(440)%3E,%20%3CProdsale:%20Prodsale%20object%20(441)%3E,%20%3CProdsale:%20Prodsale%20object%20(442)%3E,%20%3CProdsale:%20Prodsale%20object%20(443)%3E,%20%3CProdsale:%20Prodsale%20object%20(444)%3E,%20%3CProdsale:%20Prodsale%20object%20(445)%3E,%20%3CProdsale:%20Prodsale%20object%20(446)%3E,%20%3CProdsale:%20Prodsale%20object%20(447)%3E,%20%3CProdsale:%20Prodsale%20object%20(448)%3E,%20%3CProdsale:%20Prodsale%20object%20(449)%3E,%20%3CProdsale:%20Prodsale%20object%20(450)%3E,%20%3CProdsale:%20Prodsale%20object%20(466)%3E,%20%3CProdsale:%20Prodsale%20object%20(467)%3E,%20%3CProdsale:%20Prodsale%20object%20(468)%3E,%20'...(remaining%20elements%20truncated)...'%5D%3E%7D/ HTTP/1.1" 200 124877
[22/Feb/2018 19:27:13] "GET /huud/searchdatesale/ HTTP/1.1" 200 3082
[22/Feb/2018 19:27:15] "POST /huud/searchdatesale/ HTTP/1.1" 302 0
[22/Feb/2018 19:27:16] "GET /huud/searchdresults/%7B't_result':%20%3CQuerySet%20%5B%3CProdsale:%20Prodsale%20object%20(434)%3E,%20%3CProdsale:%20Prodsale%20object%20(435)%3E,%20%3CProdsale:%20Prodsale%20object%20(436)%3E,%20%3CProdsale:%20Prodsale%20object%20(437)%3E,%20%3CProdsale:%20Prodsale%20object%20(438)%3E,%20%3CProdsale:%20Prodsale%20object%20(439)%3E,%20%3CProdsale:%20Prodsale%20object%20(440)%3E,%20%3CProdsale:%20Prodsale%20object%20(441)%3E,%20%3CProdsale:%20Prodsale%20object%20(442)%3E,%20%3CProdsale:%20Prodsale%20object%20(443)%3E,%20%3CProdsale:%20Prodsale%20object%20(444)%3E,%20%3CProdsale:%20Prodsale%20object%20(445)%3E,%20%3CProdsale:%20Prodsale%20object%20(446)%3E,%20%3CProdsale:%20Prodsale%20object%20(447)%3E,%20%3CProdsale:%20Prodsale%20object%20(448)%3E,%20%3CProdsale:%20Prodsale%20object%20(449)%3E,%20%3CProdsale:%20Prodsale%20object%20(450)%3E,%20%3CProdsale:%20Prodsale%20object%20(466)%3E,%20%3CProdsale:%20Prodsale%20object%20(467)%3E,%20%3CProdsale:%20Prodsale%20object%20(468)%3E,%20'...(remaining%20elements%20truncated)...'%5D%3E%7D/ HTTP/1.1" 200 124877
[22/Feb/2018 19:27:28] "GET /huud/saledate/ HTTP/1.1" 200 1293
[22/Feb/2018 19:27:34] "POST /huud/saledate/ HTTP/1.1" 302 0
[22/Feb/2018 19:27:34] "GET /huud/results/BABY/ HTTP/1.1" 200 5375
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 22, 2018 - 19:25:00
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[22/Feb/2018 19:34:14] "GET /huud/searchdatesale/ HTTP/1.1" 200 3082
[22/Feb/2018 19:34:15] "POST /huud/searchdatesale/ HTTP/1.1" 302 0
[22/Feb/2018 19:34:16] "GET /huud/searchdresults/%7B't_result':%20%3CQuerySet%20%5B%3CProdsale:%20Prodsale%20object%20(434)%3E,%20%3CProdsale:%20Prodsale%20object%20(435)%3E,%20%3CProdsale:%20Prodsale%20object%20(436)%3E,%20%3CProdsale:%20Prodsale%20object%20(437)%3E,%20%3CProdsale:%20Prodsale%20object%20(438)%3E,%20%3CProdsale:%20Prodsale%20object%20(439)%3E,%20%3CProdsale:%20Prodsale%20object%20(440)%3E,%20%3CProdsale:%20Prodsale%20object%20(441)%3E,%20%3CProdsale:%20Prodsale%20object%20(442)%3E,%20%3CProdsale:%20Prodsale%20object%20(443)%3E,%20%3CProdsale:%20Prodsale%20object%20(444)%3E,%20%3CProdsale:%20Prodsale%20object%20(445)%3E,%20%3CProdsale:%20Prodsale%20object%20(446)%3E,%20%3CProdsale:%20Prodsale%20object%20(447)%3E,%20%3CProdsale:%20Prodsale%20object%20(448)%3E,%20%3CProdsale:%20Prodsale%20object%20(449)%3E,%20%3CProdsale:%20Prodsale%20object%20(450)%3E,%20%3CProdsale:%20Prodsale%20object%20(466)%3E,%20%3CProdsale:%20Prodsale%20object%20(467)%3E,%20%3CProdsale:%20Prodsale%20object%20(468)%3E,%20'...(remaining%20elements%20truncated)...'%5D%3E%7D/ HTTP/1.1" 200 124877
[22/Feb/2018 19:34:21] "GET /huud/saledate/ HTTP/1.1" 200 1293
[22/Feb/2018 19:34:29] "POST /huud/saledate/ HTTP/1.1" 302 0
[22/Feb/2018 19:34:30] "GET /huud/results/R/ HTTP/1.1" 200 80597
[22/Feb/2018 19:37:52] "GET /huud/searchdatesale/ HTTP/1.1" 200 3080
[22/Feb/2018 19:37:52] "GET /static/css/styles.css HTTP/1.1" 200 204
[22/Feb/2018 19:39:30] "GET /huud/searchdatesale/ HTTP/1.1" 200 3080
[22/Feb/2018 19:39:32] "POST /huud/searchdatesale/ HTTP/1.1" 302 0
[22/Feb/2018 19:39:32] "GET /huud/searchdresults/%7B't_result':%20%3CQuerySet%20%5B%3CProdsale:%20Prodsale%20object%20(434)%3E,%20%3CProdsale:%20Prodsale%20object%20(435)%3E,%20%3CProdsale:%20Prodsale%20object%20(436)%3E,%20%3CProdsale:%20Prodsale%20object%20(437)%3E,%20%3CProdsale:%20Prodsale%20object%20(438)%3E,%20%3CProdsale:%20Prodsale%20object%20(439)%3E,%20%3CProdsale:%20Prodsale%20object%20(440)%3E,%20%3CProdsale:%20Prodsale%20object%20(441)%3E,%20%3CProdsale:%20Prodsale%20object%20(442)%3E,%20%3CProdsale:%20Prodsale%20object%20(443)%3E,%20%3CProdsale:%20Prodsale%20object%20(444)%3E,%20%3CProdsale:%20Prodsale%20object%20(445)%3E,%20%3CProdsale:%20Prodsale%20object%20(446)%3E,%20%3CProdsale:%20Prodsale%20object%20(447)%3E,%20%3CProdsale:%20Prodsale%20object%20(448)%3E,%20%3CProdsale:%20Prodsale%20object%20(449)%3E,%20%3CProdsale:%20Prodsale%20object%20(450)%3E,%20%3CProdsale:%20Prodsale%20object%20(466)%3E,%20%3CProdsale:%20Prodsale%20object%20(467)%3E,%20%3CProdsale:%20Prodsale%20object%20(468)%3E,%20'...(remaining%20elements%20truncated)...'%5D%3E%7D/ HTTP/1.1" 200 147062
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 22, 2018 - 19:34:10
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[23/Feb/2018 20:38:02] "GET /huud/ HTTP/1.1" 200 1215
[23/Feb/2018 20:38:05] "GET /huud/saledate/ HTTP/1.1" 200 1357
[23/Feb/2018 20:38:07] "GET /huud/saledate/ HTTP/1.1" 200 1357
[23/Feb/2018 20:38:10] "GET /huud/ HTTP/1.1" 200 1215
[23/Feb/2018 20:38:25] "GET /huud/saledate/ HTTP/1.1" 200 1357
[23/Feb/2018 20:38:27] "GET /huud/saledate/ HTTP/1.1" 200 1357
[23/Feb/2018 20:38:31] "GET /huud/saledate/ HTTP/1.1" 200 1357
[23/Feb/2018 20:39:57] "GET /huud/ HTTP/1.1" 200 1221
[23/Feb/2018 20:39:58] "GET /huud/searchdatesale/ HTTP/1.1" 200 3150
[23/Feb/2018 20:40:00] "POST /huud/searchdatesale/ HTTP/1.1" 302 0
[23/Feb/2018 20:40:01] "GET /huud/searchdresults/2018-01-01/ HTTP/1.1" 200 106257
[23/Feb/2018 20:40:10] "GET /huud/ HTTP/1.1" 200 1221
[23/Feb/2018 20:40:13] "GET /huud/saledate/ HTTP/1.1" 200 1363
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 23, 2018 - 20:37:56
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
2018-01-01
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): huud.
Run 'python manage.py migrate' to apply them.
February 23, 2018 - 21:40:46
Django version 2.1.dev20180215184426, using settings 'huudeey.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[24/Feb/2018 13:12:28] "GET /huud/saledate/ HTTP/1.1" 200 1363
[24/Feb/2018 13:12:35] "POST /huud/saledate/ HTTP/1.1" 302 0
[24/Feb/2018 13:12:35] "GET /huud/results/House/ HTTP/1.1" 200 9120
[24/Feb/2018 13:12:40] "GET /huud/searchdatesale/ HTTP/1.1" 200 3150
[24/Feb/2018 13:12:42] "POST /huud/searchdatesale/ HTTP/1.1" 302 0
[24/Feb/2018 13:12:43] "GET /huud/searchdresults/2018-01-01/ HTTP/1.1" 200 106257
[24/Feb/2018 13:13:12] "GET /huud/searchdatesale/ HTTP/1.1" 200 3150
[24/Feb/2018 13:13:14] "POST /huud/searchdatesale/ HTTP/1.1" 302 0
[24/Feb/2018 13:13:15] "GET /huud/searchdresults/2018-01-01/ HTTP/1.1" 200 106257
[24/Feb/2018 13:13:24] "GET /huud/ HTTP/1.1" 200 1221
